const { Router } = require('express')
const { parteDiaroController, abastecimientoController, abastecimientoMesActualController, parteDiaroMesActualController, abastecimientoMesAnteriorController, findAllRegionsController, findAllLineController, findAllSublineController, findAllGroupAlmacenController, abastecimientoPorFechaController, abastecimientoFechaAnualController, abastecimientoFecha24MesesController } = require('../controller/finanzas.controller')
const { validarToken } = require('../../../middleware/validar_token.middleware')
const { validarCampos } = require('../../../middleware/validar_campos.middleware')
const router = Router()

router.post('/parte-diaria', [validarToken, validarCampos], parteDiaroController)
router.post('/abastecimiento', [validarToken, validarCampos], abastecimientoController)
router.get('/abastecimiento-mes-anterior', [validarToken, validarCampos], abastecimientoMesAnteriorController)
router.get('/abastecimiento-mes-actual', [validarToken, validarCampos], abastecimientoMesActualController)
router.get('/abastecimiento-por-fecha', [validarToken, validarCampos], abastecimientoPorFechaController)
router.get('/abastecimiento-anual', [validarToken, validarCampos], abastecimientoFechaAnualController)
router.get('/abastecimiento-24-meses', [validarToken, validarCampos], abastecimientoFecha24MesesController)
router.get('/parte-diario-mes-actual', [validarToken, validarCampos], parteDiaroMesActualController)
router.get('/find-all-regions', [validarToken, validarCampos], findAllRegionsController)
router.get('/find-all-line', [validarToken, validarCampos], findAllLineController)
router.get('/find-all-subline', [validarToken, validarCampos], findAllSublineController)
router.get('/find-all-group-almacen', [validarToken, validarCampos], findAllGroupAlmacenController)

module.exports = router